---
# TEMPLATE GENERATED VIA COOKIECUTTER. ADAPT ACCORDINGLY

Transform:
  - AWS::Serverless-2016-10-31
Description: Template for function {{ cookiecutter.function_name }}
Parameters:
  NewAliasName:
    Type: String
    Default: 'live'
  ReleaseNewAlias:
    AllowedValues:
      - 'True'
      - 'False'
    Default: 'True'
    Type: String
Conditions:
  ReleaseAlias: !Equals
    - !Ref 'ReleaseNewAlias'
    - 'True'
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: {{ cookiecutter.function_name }}.zip
      AutoPublishAlias: !If
        - ReleaseAlias
        - !Ref NewAliasName
        - !Ref 'AWS::NoValue'
      Environment:
        Variables:
          Key: Value
      Handler: function.lambda_handler
      Layers:
        - arn:aws:lambda:eu-west-1:373709687836:layer:ozone:9
      MemorySize: 256
      Role: !GetAtt 'LambdaFunctionRole.Arn'
      Runtime: python3.7
      Timeout: 15
      FunctionName: !Ref 'AWS::NoValue'
  LambdaFunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - !Sub 'lambda.${AWS::URLSuffix}'
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
    Type: AWS::IAM::Role
